### ISSUE TITLE
Make different input fields for comments and pro-tips

### ISSUE THREAD

**Issue by delaneyrae** [devvmh/hackthesymphony#2]
We need different fields for comments and pro-tips so they can be displayed differently and more impact fully through CSS. It's likely to be more sustainable for the symphony to just treat these as different things rather than assign classes to them.

**Comment by devvmh** [comment]
OK this is implemented.

@delaneyrae I'm closing this issue; I'm assuming making protips look nice will fall under the general "make everything look nice" ticket.

Currently protips are bolded, and show up right underneath comments. We'll need to add them to the database fixtures to make this field useful ( @chelseamills )
